import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Make sure this file exists — generated by FlutterFire CLI

import 'package:projecho/pages/onboard.dart';
import 'package:projecho/pages/login.dart';


import 'package:projecho/pages/Signup/enteruname.dart';
import 'package:projecho/pages/Signup/usertype.dart';
import 'package:projecho/pages/Signup/birthdate.dart';
import 'package:projecho/pages/Signup/gender.dart';
import 'package:projecho/pages/Signup/auth.dart';
import 'package:projecho/pages/Signup/createpass.dart';
import 'package:projecho/pages/Signup/otp.dart';
import 'package:projecho/pages/Signup/welcome.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => const MyOnboardingScreen(),
        '/login': (context) => const LoginScreen(),

        // register screens
        '/username': (context) => const Usernamescreen(),
        '/usertype': (context) => const UserTypeScreen(),
        '/birthdate': (context) => const BirthdateScreen(),
        '/gender': (context) => const GenderSelectionScreen(),
        '/auth': (context) => const RegistrationMethodScreen(),
        '/password': (context) => const PasswordScreen(),
        '/otp': (context) {
          final args = ModalRoute.of(context)!.settings.arguments as Map<String, dynamic>;
          return OTPScreen(
            verificationId: args['verificationId'],
            phoneNumber: args['phoneNumber'],
          );
        },
        '/welcome': (context) => const WelcomeScreen(),
      },
    );
  }
}
